version: 2.1

jobs:
  python-version-check-1:
    docker:
      - image: cimg/python:3.8.14
    steps:
      - run: git --version
      - checkout
  python-version-check-2:
    docker:
      - image: cimg/python:3.10.12
    steps:
      - run: git --version
      - checkout

workflows:
  setup-workflow:
    jobs:
      - python-version-check-1
      - python-version-check-2
