version: 2.1

jobs:
  python-version-check:
    docker:
      - image: cimg/python:3.8.14
    resource_class: large
    steps:
      - run: git --version
      - checkout
  python-version-check-2:
    docker:
      - image: cimg/python:3.9.0
    resource_class: large
    steps:
      - run: git --version
      - checkout
  python-version-check-3:
    docker:
      - image: cimg/python:3.10.12
    resource_class: large
    steps:
      - run: git --version
      - checkout

workflows:
  setup-workflow:
    jobs:
      - python-version-check
      - python-version-check-2
      - python-version-check-3
