version: 2.1

jobs:
  python-version-check:
    steps:
      - run: git --version
      - checkout

workflows:
  setup-workflow:
    jobs:
      - python-version-check:
          docker:
            - image: cimg/python:3.8.14
      - python-version-check:
          docker:
            - image: cimg/python:3.9.0
      - python-version-check:
          docker:
            - image: cimg/python:3.10.12
